server:
    port: 8080
    servlet:
        contextPath: /api/v1
spring:
    application:
        name: App Sales v2
    config:
        activate:
            onProfile: ${SPRING_PROFILES_ACTIVE:test}
    mvc:
        pathmatch:
            matchingStrategy: ANT_PATH_MATCHER
    security:
        oauth2:
            client:
                registration:
                    jwtDuration: ${JWT_DURATION:86400}
                    jwtSecret: ${JWT_SECRET:my-jwt-secret}
                    uaa:
                        clientId: ${CLIENT_ID:my-client-id}
                        clientSecret: ${CLIENT_SECRET:my-client-secret}
    email:
        host: smtp.mail.com
        username: abc@gmail.com
        passowrd: xyz
        from: abc@gmail.com
        properties:
            mail.transport.protocol: smtp
            mail.smtp.port: 587
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
# =================================
# = Logging
# =================================
logging:
    level:
        org.springframework: ERROR
        org.flywaydb: ERROR
# =================================
# = App Congig
# =================================
appConfig:
    maxSize: 50
    email:
        templates:
            created:
                subject: Novo agendamento de sala criado
                templateName: template-created.html
            updated:
                subject: Agendamento de sala alterado
                templateName: template-updated.html
            deleted:
                subject: Agendamento de sala excluido
                templateName: template-deleted.html