spring:
    datasource:
        driverClassName: org.h2.Driver
        password:
        url: jdbc:h2:mem:testdb
        username: sa
    environment: test
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
    jpa:
        database: H2
        properties:
            ddl-auto: create
            dialect: org.hibernate.dialect.H2Dialect
            hibernate:
                format_sql: true
                open-in-view: false
        platform: h2
        show-sql: false
    sql:
        init:
            platform: h2
