server:
  port: 8080
  servlet:
    contextPath: /api/v1
spring:
  application:
    name: App Sales v2
  config:
    activate:
      onProfile: ${SPRING_PROFILES_ACTIVE:test}
  mvc:
    pathmatch:
      matchingStrategy: ANT_PATH_MATCHER
  security:
    jwt:
      duration: ${JWT_DURATION:86400}
    client-id: ${CLIENT_ID:myclientid}
    client-secret: ${CLIENT_SECRET:myclientsecret}
  cors:
    origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}
  email:
    host: smtp.mail.com
    username: claudiocardo@gmail.com
    passowrd: Lima123@
    from: claudiocardo@gmail.com
    properties:
      mail.transport.protocol: smtp
      mail.smtp.port: 587
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
# =================================
# = Logging
# =================================
logging:
  level:
    org.springframework: ERROR
    org.flywaydb: ERROR
# =================================
# = App Congig
# =================================
app:
  maxSize: 50
  email:
    templates:
      created:
        subject: Novo agendamento de sala criado
        templateName: template-created.html
      updated:
        subject: Agendamento de sala alterado
        templateName: template-updated.html
      deleted:
        subject: Agendamento de sala excluido
        templateName: template-deleted.html