spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/imagelite?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: postgres
  environment: development
  jpa:
    datasource: POSTGRESQL
    propertites:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              createTarget:
                create: sql
            createSource: metadata
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
      format-sql: true
      open-in-view: false
      hbm2ddl:
        delimiter: ;
  show-sql: true
  sql:
    init:
      platform: postgres