server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /api/v1
spring:
  config:
    name: App Sales v2
  application:
    name: App Sales v2
  profiles:
    active:
      - ${SPRING_PROFILES_ACTIVE:test}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:20}MB
      max-request-size: ${MAX_REQUEST_SIZE:20}MB
  security:
    oauth2:
      client:
        provider: OAuth2provider
        registration:
          OAuth2provider:
            clientId: ${CLIENT_ID:myclientid}
            clientSecret: ${CLIENT_SECRET:myclientsecret}


    jwt:
      duration: ${JWT_DURATION:86400}
  #corsOrigins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}
  mail:
    host: smtp.mail.com
    username: claudiocardo@gmail.com
    password: Lima123@
    #from: claudiocardo@gmail.com
    protocol: smtp
    properties:
      - port: 587
      - auth: true
      - starttls: true




# =================================
# = Logging
# =================================
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %thread ${PID} [%X{correlationId}] %-5level %logger{36} - %class{1} - %msg%n"
  level:
    root: error
    sql: error
    web: error
# =================================
# = App Congig
# =================================
app:
  maxSize: 50
  email:
    templates:
      created:
        subject: Novo agendamento de sala criado
        templateName: template-created.html
      updated:
        subject: Agendamento de sala alterado
        templateName: template-updated.html
      deleted:
        subject: Agendamento de sala excluido
        templateName: template-deleted.html
